version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE=tarefas
      - S3_BUCKET_NAME= Pendente de nome
      - SQS_QUEUE_URL= Pendente de link(url)
      - FLASK_APP=app
      - FLASK_ENV=development
    volumes:
      - .:/App
